export const BEST_SELLER_FETCHED = 'BEST_SELLER_FETCHED';
export const BEST_SELLER_ERROR = 'BEST_SELLER_ERROR';

export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_FETCH_ERROR = 'PRODUCT_FETCH_ERROR';

