export const USER_SIGNIN_ATTEMPT = 'USER_SIGNIN_ATTEMPT';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_SIGNUP_ATTEMPT = 'USER_SIGNUP_ATTEMPT';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';


export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
